.\" Manpage for generator.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "24 Feb 2018" "1.0" "generator man page"

.SH NAME
generator \-  generate files with the models information (only generate the vertices for the model)


.SH SYNOPSIS
generator MODEL FILE [specs ...]


.SH DESCRIPTION
generator is a file generator of models ...
.LP
the following models are avaiable:
.RS 3
.LP
\fbplane\fr 
.LP
\fbbox\fr x_dim y_dim z_dim n_div
.LP
\fbsphere\fr radius slices stacks
.LP
\fbcone\fr radius height slice stacks


.SH OPTIONS
The generator does not take any options.


.SH SEE ALSO
engine(1)


.SH BUGS
No known bugs.


.SH AUTHOR
Adriano, Artur, Luis, Vasco
